update build script to copt NetworkMonitor.dll

diff --git a/build-run-docker b/build-run-docker
--- a/build-run-docker
+++ b/build-run-docker
@@ -18,6 +18,11 @@ if ! git pull "$REPO_URL"; then
 fi
 
 # Step 2: Build and publish the Docker container
+if ! dotnet publish NetworkMonitorProcessor-debian12.csproj --os linux --arch x64 -c Release; then
+    echo "Failed to publish the Docker container. Exiting..."
+    exit 1
+fi
+cp ~/code/NetworkMonitorProcessor/bin/Release/net9.0/linux-x64/NetworkMonitor.dll ~/code/NetworkMonitorProcessor/openssl-3.3.1/bin/dlls/
 if ! dotnet publish NetworkMonitorProcessor-debian12.csproj --os linux --arch x64 /t:PublishContainer -c Release; then
     echo "Failed to publish the Docker container. Exiting..."
     exit 1
